databases:
 - name: vite_rails_demo
   databaseName: vite_rails_demo
   user: vite_rails_demo

services:
 - type: web
   name: vite_rails_demo
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: vite_rails_demo
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false